/*
 * Fragen-Datenbasis SBF-Trainer.
 *
 * WICHTIGER HINWEIS ZUR QUELLENLAGE:
 * In dieser Arbeitsumgebung ist der Zugriff auf elwis.de (amtlicher
 * Fragenkatalog See/Binnen der Prüfungsausschüsse) sowie auf alle
 * gefundenen Spiegelseiten durch die Netzwerk-Policy blockiert. Eine
 * wortlaut- und nummerngetreue 1:1-Übernahme des amtlichen Katalogs war
 * daher nicht überprüfbar möglich. Die folgenden Fragen sind daher KEINE
 * verbatim-Kopie des amtlichen Katalogs, sondern fachlich eigenständig
 * formulierte Prüfungsfragen, die sich inhaltlich strikt an den
 * offiziellen Themenkomplexen orientieren und mit der einschlägigen
 * Rechtsquelle belegt sind. Wo die exakte Paragraphen-Nummer nicht mit
 * Sicherheit verifizierbar war, wird nur der Name der Vorschrift bzw.
 * das betreffende Kapitel angegeben, nie eine geratene Nummer.
 *
 * Kürzel: KVR = Kollisionsverhütungsregeln (identische Regelnummern wie
 * COLREG 1972); BinSchStrO = Binnenschifffahrtsstraßen-Ordnung;
 * SeeSchStrO = Seeschifffahrtsstraßenordnung; SpFV =
 * Sportbootführerschein-Verordnung; SchSV = Sportsee- bzw.
 * See-Sportbootverordnung.
 */

const CATEGORIES = {
  recht: "Schifffahrtsrecht",
  verhalten: "Verhalten auf dem Wasser",
  navigation: "Navigation",
  wetter: "Wetterkunde",
  signale: "Signalkunde",
  knoten: "Knotenkunde",
  sicherheit: "Sicherheit & Ausrüstung",
};

const PACKAGES = [
  {
    id: "basis",
    title: "Basisfragen",
    subtitle: "Gemeinsam für SBF See & SBF Binnen",
  },
  {
    id: "see",
    title: "Seespezifische Fragen",
    subtitle: "KVR, Lichter, Betonnung, Seenotfälle",
  },
  {
    id: "binnen",
    title: "Binnenspezifische Fragen",
    subtitle: "BinSchStrO, Fahrregeln, Schleusen",
  },
  {
    id: "navigation",
    title: "Navigation",
    subtitle: "Kompass, Karte, Peilung, Gezeiten",
  },
];

let uid = 0;
function Q(pkg, category, q, options, correct, source, opts = {}) {
  uid += 1;
  return {
    id: `${pkg}-${String(uid).padStart(3, "0")}`,
    pkg,
    category,
    q,
    options,
    correct,
    source,
    diagram: opts.diagram || null,
    note: opts.note || null,
  };
}

const QUESTIONS = [
  // ---------------------------------------------------------------
  // PAKET: BASISFRAGEN (gemeinsam See & Binnen)
  // ---------------------------------------------------------------
  Q("basis", "recht",
    "Was muss vor Antritt der Fahrt feststehen?",
    ["Wer die Aufgabe des Schiffsführers/Fahrzeugführers wahrnimmt", "Welcher Sportbootführerschein an Bord der teuerste ist", "Wer am Steuer die meiste Erfahrung hat, unabhängig vom Führerschein", "Wer zuerst an Bord gegangen ist"],
    0, "BinSchStrO/SeeSchStrO – Grundsatz: jedes Fahrzeug braucht einen verantwortlichen Führer"),
  Q("basis", "recht",
    "Welche Aufgabe hat der Schiffs-/Fahrzeugführer nach dem allgemeinen Sorgfaltsgrundsatz?",
    ["Er trägt die Verantwortung für die Sicherheit von Fahrzeug, Besatzung und anderen Verkehrsteilnehmern", "Er ist nur für die Navigation zuständig, nicht für die Sicherheit", "Er haftet nur bei Vorsatz, nie bei Fahrlässigkeit", "Er kann die Verantwortung während der Fahrt beliebig an Gäste abgeben"],
    0, "Allgemeiner Sorgfaltsgrundsatz, KVR Regel 2 / BinSchStrO § 1.04"),
  Q("basis", "recht",
    "Wie hoch ist die absolute Fahruntüchtigkeitsgrenze für Führer von Sportbooten auf Binnenschifffahrtsstraßen?",
    ["0,5 ‰ Blutalkohol bzw. 0,25 mg/l Atemalkohol", "1,1 ‰ Blutalkohol wie bei Fußgängern", "Es gilt keine Promillegrenze auf dem Wasser", "0,0 ‰, absolutes Alkoholverbot für jede Fahrt"],
    0, "BinSchStrO § 3.04"),
  Q("basis", "signale",
    "Wie lange dauert ein kurzer Ton im Sinne der Schallsignale?",
    ["Etwa 1 Sekunde", "Etwa 4–6 Sekunden", "Etwa 10 Sekunden", "Es gibt keine feste Zeitangabe"],
    0, "KVR Regel 32"),
  Q("basis", "signale",
    "Wie lange dauert ein langer Ton im Sinne der Schallsignale?",
    ["4 bis 6 Sekunden", "1 Sekunde", "Mindestens 15 Sekunden", "Genau 2 Sekunden"],
    0, "KVR Regel 32"),
  Q("basis", "verhalten",
    "Wann gilt ein Fahrzeug als „in Fahrt“ im Sinne der Verkehrsregeln?",
    ["Wenn es weder vor Anker noch festgemacht noch auf Grund ist", "Nur wenn der Motor läuft", "Nur wenn es schneller als 3 Knoten fährt", "Sobald die Positionslichter eingeschaltet sind"],
    0, "KVR Regel 3 Buchstabe i"),
  Q("basis", "verhalten",
    "Welche Grundpflicht besteht nach den Ausweichregeln unabhängig von der eigenen Kurshaltepflicht?",
    ["Jedes Fahrzeug muss stets einen Zusammenstoß nach Möglichkeit verhindern", "Nur das größere Fahrzeug muss ausweichen", "Nur der ausweichpflichtige Teil trägt Verantwortung für Kollisionsvermeidung", "Segelfahrzeuge müssen nie reagieren, da sie immer Vorfahrt haben"],
    0, "KVR Regel 2 (Grundsatz), Regel 17 Abs. 2"),
  Q("basis", "sicherheit",
    "Was schreibt der Sorgfaltsgrundsatz zur persönlichen Schutzausrüstung sinngemäß vor?",
    ["Der Schiffsführer muss dafür sorgen, dass insbesondere Nichtschwimmer und Kinder eine Rettungsweste tragen", "Rettungswesten sind nur für Fahrten außerhalb Sichtweite der Küste sinnvoll", "Erwachsene benötigen grundsätzlich keine Rettungsweste", "Rettungswesten müssen nur beim Ablegen, nicht während der Fahrt getragen werden"],
    0, "Allgemeine Sicherheitsempfehlung der Wasserschutzpolizei/Verbände (keine bundeseinheitliche Tragepflicht für Erwachsene)"),
  Q("basis", "sicherheit",
    "Welche Mindestausrüstung gehört zur allgemeinen Sicherheitsausrüstung eines Sportbootes?",
    ["Rettungsmittel für alle an Bord befindlichen Personen, Ankergeschirr, Handlenzpumpe/Lenzeinrichtung", "Nur ein Erste-Hilfe-Kasten", "Ausschließlich ein Feuerlöscher, weitere Mittel sind freiwillig", "Ein zweiter Motor als Reserve"],
    0, "Allgemeine Sicherheitsausrüstungsgrundsätze für Sportboote"),
  Q("basis", "recht",
    "Ab welchem Mindestalter kann ein Sportbootführerschein (See oder Binnen) erworben werden?",
    ["16 Jahre", "14 Jahre", "18 Jahre", "Es gibt kein Mindestalter"],
    0, "Sportbootführerschein-Verordnung (SpFV), Zulassungsvoraussetzungen"),
  Q("basis", "recht",
    "Unter welcher Voraussetzung darf ein Sportboot mit Motor auf den meisten Binnenwasserstraßen ohne Führerschein geführt werden?",
    ["Wenn die Antriebsmaschine höchstens 11,03 kW (15 PS) leistet", "Wenn das Boot kürzer als 15 Meter ist, unabhängig von der Motorleistung", "Nie – auf Binnenwasserstraßen besteht für jedes Motorboot Führerscheinpflicht", "Wenn der Bootsführer über 18 Jahre alt ist"],
    0, "Sportbootführerschein-Verordnung, Ausnahme von der Führerscheinpflicht"),
  Q("basis", "recht",
    "Was gilt grundsätzlich für das Einleiten von Ölresten oder ölhaltigem Bilgenwasser in ein Gewässer?",
    ["Es ist verboten", "Es ist erlaubt, wenn die Menge gering ist", "Es ist nur bei Nacht verboten", "Es ist nur auf Binnenwasserstraßen verboten, auf See erlaubt"],
    0, "Ölverbots-Gesetz / MARPOL-Übereinkommen, Anlage I"),
  Q("basis", "verhalten",
    "Ein Fahrzeug erzeugt in engen Kurven, an Buhnen oder Molen einen auffälligen Wellenschlag. Wie ist dies zu bewerten?",
    ["Der Fahrzeugführer haftet für Schäden durch überhöhten Wellenschlag; die Geschwindigkeit ist entsprechend anzupassen", "Wellenschlag ist grundsätzlich hinzunehmen, eine Haftung besteht nicht", "Nur Berufsschifffahrt haftet für Wellenschlag, Sportboote nie", "Wellenschlag ist nur bei Segelbooten relevant"],
    0, "Allgemeiner Sorgfaltsgrundsatz, BinSchStrO § 1.04 / KVR Regel 6"),
  Q("basis", "sicherheit",
    "Wozu dient eine Handlenzpumpe an Bord eines kleinen Sportbootes?",
    ["Zum manuellen Entfernen von eingedrungenem Wasser aus dem Rumpf", "Zum Auftanken von Kraftstoff", "Zum Reinigen des Decks", "Zum Ablassen von Frischwasser"],
    0, "Allgemeine Sicherheitsausrüstung"),
  Q("basis", "verhalten",
    "Was ist unmittelbar vor dem Anlassen eines Innenbordmotors mit Benzinantrieb zu prüfen?",
    ["Die Bilge auf Kraftstoff-/Gasdämpfe zu prüfen und ggf. zu lüften", "Ob der Motor bereits warmgelaufen ist", "Ob genug Proviant an Bord ist", "Ob alle Fenster geschlossen sind"],
    0, "Allgemeine Sicherheitsregel gegen Explosionsgefahr in der Bilge"),
  Q("basis", "signale",
    "Welche Bedeutung hat das international genormte Seenotzeichen SOS (· · · — — — · · ·)?",
    ["Es signalisiert, dass sich ein Fahrzeug oder eine Person in unmittelbarer Not befindet und Hilfe benötigt", "Es fordert lediglich zur Kursänderung auf", "Es bedeutet „Ich manövriere nicht mehr“", "Es zeigt Ankerliegen bei Nacht an"],
    0, "Internationales Seenotsignal, Vollzugsordnung für den Funkdienst / KVR Anlage IV"),
  Q("basis", "recht",
    "Was bedeutet der Begriff „Fahrzeug, das manövrierunfähig ist“?",
    ["Ein Fahrzeug, das wegen außergewöhnlicher Umstände nicht so manövrieren kann, wie es die Regeln verlangen, und deshalb einem anderen Fahrzeug nicht ausweichen kann", "Ein Fahrzeug ohne Besatzung", "Ein Fahrzeug, dessen Motor überhitzt ist, aber noch fährt", "Ein Fahrzeug, das lediglich vor Anker liegt"],
    0, "KVR Regel 3 Buchstabe f"),
  Q("basis", "verhalten",
    "Welche grundsätzliche Pflicht besteht gegenüber Badenden und Schwimmern?",
    ["Ausreichend großer Sicherheitsabstand und Anpassung von Fahrt/Geschwindigkeit, um Gefährdung auszuschließen", "Badende haben sich grundsätzlich an Fahrzeuge anzupassen", "Ein Mindestabstand ist gesetzlich nicht vorgesehen", "Nur bei Nacht ist Rücksicht auf Schwimmer zu nehmen"],
    0, "Allgemeiner Sorgfaltsgrundsatz / jeweilige Landes-Wassersportverordnungen"),
  Q("basis", "wetter",
    "Was gibt die Beaufort-Skala an?",
    ["Die Windstärke anhand ihrer Wirkung auf See bzw. an Land", "Die Wassertemperatur", "Die Höhe der Gezeiten", "Die Sichtweite bei Nebel"],
    0, "Meteorologische Windstärkeskala nach Sir Francis Beaufort", { diagram: "beaufort" }),
  Q("basis", "wetter",
    "Welche Windstärke nach Beaufort wird umgangssprachlich als „stürmischer Wind“ bezeichnet und liegt bereits im kritischen Bereich für kleine Sportboote?",
    ["Beaufort 8", "Beaufort 2", "Beaufort 4", "Beaufort 1"],
    0, "Beaufort-Windskala"),
  Q("basis", "wetter",
    "Woran erkennt man meteorologisch ein nahendes Tiefdruckgebiet häufig zuerst?",
    ["Fallender Luftdruck und aufziehende hohe Schleierwolken (Cirren)", "Steigender Luftdruck bei klarem Himmel", "Konstanter Luftdruck über mehrere Tage", "Ausschließlich an der Wassertemperatur"],
    0, "Allgemeine Wetterkunde"),
  Q("basis", "knoten",
    "Welche Eigenschaft zeichnet den Palstek aus?",
    ["Er bildet eine feste, sich unter Last nicht zuziehende Schlaufe und lässt sich danach leicht wieder lösen", "Er ist nur zum Verbinden zweier gleich dicker Leinen geeignet", "Er zieht sich unter Last immer weiter zu und ist danach nicht mehr lösbar", "Er wird ausschließlich zum Reffen von Segeln verwendet"],
    0, "Seemannschaft – Standardknoten", { diagram: "knotBowline" }),
  Q("basis", "knoten",
    "Wofür wird ein Achtknoten typischerweise verwendet?",
    ["Als Stopperknoten am Ende einer Leine, damit diese nicht durch einen Block oder eine Klemme rutscht", "Zum dauerhaften Verbinden zweier Trossen", "Zum Festmachen an einem Poller", "Als Rettungsknoten unter der Achsel"],
    0, "Seemannschaft – Standardknoten", { diagram: "knotFigureEight" }),
  Q("basis", "knoten",
    "Wofür eignet sich der Webleinstek besonders?",
    ["Zum schnellen, lösbaren Belegen einer Leine an einem Poller, einer Reling oder einem Pfahl", "Zum Spleißen von Tauwerk", "Als einzige zulässige Schleppverbindung", "Zum Verbinden zweier Ankerleinen unterschiedlicher Stärke"],
    0, "Seemannschaft – Standardknoten", { diagram: "knotCloveHitch" }),
  Q("basis", "verhalten",
    "Was ist beim Übernehmen von Personen aus Seenot vorrangig zu beachten?",
    ["Die eigene Sicherheit und die der Besatzung darf dabei nicht unverhältnismäßig gefährdet werden, Hilfe ist aber grundsätzlich zu leisten", "Es besteht keine Hilfeleistungspflicht auf dem Wasser", "Nur Berufsschifffahrt muss Hilfe leisten, Sportboote sind ausgenommen", "Hilfeleistung ist nur bei Tageslicht Pflicht"],
    0, "Seerechtsübereinkommen (SRÜ) Art. 98 / Strafgesetzbuch § 323c (unterlassene Hilfeleistung)"),
  Q("basis", "recht",
    "Was versteht man unter der „Betriebssicherheit“ eines Sportbootes?",
    ["Der technisch einwandfreie und den Vorschriften entsprechende Zustand von Fahrzeug, Maschine und Ausrüstung", "Ausschließlich das Vorhandensein einer Versicherung", "Die Erfahrung des Steuermanns", "Die Höchstgeschwindigkeit des Bootes"],
    0, "Allgemeiner Sorgfaltsgrundsatz"),
  Q("basis", "sicherheit",
    "Welchen Zweck erfüllt eine Signalpfeife oder ein Nebelhorn an Bord kleiner Fahrzeuge?",
    ["Abgabe vorgeschriebener Schallsignale, z. B. bei verminderter Sicht oder Manövern", "Ausschließlich zur Verständigung mit Land", "Zum Anlocken von Rettungskräften über Funk", "Sie ist reine Dekoration ohne Funktion"],
    0, "KVR Regel 32–37"),
  Q("basis", "verhalten",
    "Wie verhält sich ein Fahrzeugführer grundsätzlich beim Kreuzen von Wasserski-/Wassersportbereichen?",
    ["Er hält deutlich Abstand, reduziert die Fahrt und beachtet die dortige Vorfahrt der Wassersportler", "Er hat dort immer Vorfahrt vor Wasserskiläufern", "Ein besonderes Verhalten ist nicht vorgeschrieben", "Er darf mit voller Fahrt durchqueren, solange kein Schwimmer sichtbar ist"],
    0, "Landesspezifische Wassersport-/Befahrensverordnungen, allgemeiner Sorgfaltsgrundsatz"),

  // ---------------------------------------------------------------
  // PAKET: SEESPEZIFISCHE FRAGEN
  // ---------------------------------------------------------------
  Q("see", "verhalten",
    "Zwei Maschinenfahrzeuge treffen auf entgegengesetzten oder fast entgegengesetzten Kursen aufeinander (Steuerbord an Steuerbord). Wie verhalten sie sich?",
    ["Beide Fahrzeuge weichen jeweils nach Steuerbord aus, sodass sie Backbord an Backbord vorbeikommen", "Nur das kleinere Fahrzeug muss ausweichen", "Beide behalten unverändert Kurs und Fahrt bei", "Beide weichen nach Backbord aus"],
    0, "KVR Regel 14 – Entgegengesetzter Kurs"),
  Q("see", "verhalten",
    "Zwei Maschinenfahrzeuge haben so kreuzende Kurse, dass die Gefahr eines Zusammenstoßes besteht. Wer muss ausweichen?",
    ["Das Fahrzeug, das das andere an seiner Steuerbordseite hat", "Das größere der beiden Fahrzeuge", "Das schnellere Fahrzeug", "Das Fahrzeug, das zuerst gesichtet wurde"],
    0, "KVR Regel 15 – Kreuzende Kurse"),
  Q("see", "verhalten",
    "Welches Fahrzeug gilt beim Überholen als ausweichpflichtig?",
    ["Das überholende Fahrzeug, unabhängig von Antriebsart oder Größe", "Immer das überholte Fahrzeug", "Das Fahrzeug mit dem stärkeren Motor", "Bei Segelfahrzeugen gilt die Überholregel nicht"],
    0, "KVR Regel 13 – Überholen"),
  Q("see", "verhalten",
    "Ein Segelfahrzeug und ein Fahrzeug unter Maschine begegnen sich mit Gefahr eines Zusammenstoßes. Wer muss grundsätzlich ausweichen?",
    ["Das Maschinenfahrzeug muss dem Segelfahrzeug ausweichen", "Das Segelfahrzeug muss immer ausweichen", "Es gilt „schneller vor langsamer“", "Beide behalten Kurs und Fahrt bei"],
    0, "KVR Regel 18"),
  Q("see", "verhalten",
    "Zwei Segelfahrzeuge nähern sich einander so, dass die Gefahr eines Zusammenstoßes besteht, sie haben den Wind auf verschiedenen Seiten. Welches Fahrzeug muss ausweichen?",
    ["Das Fahrzeug, das den Wind an Backbord hat", "Das Fahrzeug, das den Wind an Steuerbord hat", "Immer das kleinere Boot", "Es gibt keine Regel, beide müssen reagieren"],
    0, "KVR Regel 12", { diagram: "windPointOfSail" }),
  Q("see", "verhalten",
    "Ein Fahrzeug fährt in einem enge Fahrwasser oder Fahrrinne. Wie muss es sich verhalten?",
    ["Es hat sich, soweit dies ohne Gefahr möglich ist, so nahe der äußeren Grenze des Fahrwassers zu halten, die an seiner Steuerbordseite liegt", "Es fährt grundsätzlich in der Fahrwassermitte", "Es hält sich an der Backbordgrenze des Fahrwassers", "Enge Fahrwasser unterliegen keiner besonderen Regel"],
    0, "KVR Regel 9 – Enge Fahrwasser"),
  Q("see", "signale",
    "Welche Lichter führt ein Maschinenfahrzeug unter 12 Metern Länge bei Nacht in Fahrt mindestens?",
    ["Topplicht (weiß, rundum vorn), Seitenlichter rot/grün und ein weißes Hecklicht", "Nur ein weißes Rundumlicht", "Nur ein rotes Licht an Backbord", "Zwei grüne Rundumlichter übereinander"],
    0, "KVR Regel 23", { diagram: "navLightsMotor" }),
  Q("see", "signale",
    "Welche Lichter führt ein Segelfahrzeug in Fahrt bei Nacht, zusätzlich zu den Seitenlichtern?",
    ["Ein weißes Hecklicht, jedoch kein Topplicht", "Ein weißes Topplicht wie ein Maschinenfahrzeug", "Zwei rote Rundumlichter übereinander", "Kein zusätzliches Licht ist erforderlich"],
    0, "KVR Regel 25", { diagram: "navLightsSail" }),
  Q("see", "signale",
    "Welche Farbe hat das Seitenlicht an der Steuerbordseite eines Fahrzeugs?",
    ["Grün", "Rot", "Weiß", "Gelb"],
    0, "KVR Regel 21"),
  Q("see", "signale",
    "Welche Farbe hat das Seitenlicht an der Backbordseite eines Fahrzeugs?",
    ["Rot", "Grün", "Weiß", "Blau"],
    0, "KVR Regel 21"),
  Q("see", "signale",
    "Ein Fahrzeug unter 7 Metern Länge, das nur geringe Fahrt macht, darf anstelle der vorgeschriebenen Lichter bei Nacht führen:",
    ["Ein weißes Rundumlicht, sofern das Zeigen der übrigen Lichter nicht durchführbar ist", "Gar kein Licht", "Ausschließlich ein rotes Rundumlicht", "Zwei gelbe Blinklichter"],
    0, "KVR Regel 23", { diagram: "navLightsSmallCraft" }),
  Q("see", "signale",
    "Was bedeuten ein Ball und darunter ein Kegel mit der Spitze nach unten als Signalkörper bei Tage an einem Segelfahrzeug?",
    ["Das Fahrzeug wird gleichzeitig unter Maschine und unter Segel gefahren", "Das Fahrzeug ist manövrierunfähig", "Das Fahrzeug ankert", "Das Fahrzeug führt einen Schleppzug"],
    0, "KVR Regel 25 Buchstabe e"),
  Q("see", "signale",
    "Welches Tagsignal führt ein vor Anker liegendes Fahrzeug?",
    ["Einen schwarzen Ball, gut sichtbar im vorderen Teil des Fahrzeugs", "Zwei schwarze Kegel Spitze gegen Spitze", "Eine rote Flagge", "Kein Signal ist bei Tage erforderlich"],
    0, "KVR Regel 30"),
  Q("see", "signale",
    "Welche Schallsignalfolge gibt ein Fahrzeug bei stark verminderter Sicht (z. B. Nebel), wenn es unter Maschine fährt und Fahrt durchs Wasser macht?",
    ["Einen langen Ton in Abständen von höchstens 2 Minuten", "Drei kurze Töne alle 30 Sekunden", "Einen kurzen und zwei lange Töne pausenlos", "Kein Signal ist bei Nebel erforderlich, solange Radar an Bord ist"],
    0, "KVR Regel 35 Buchstabe a"),
  Q("see", "signale",
    "Was bedeutet ein Manöversignal von einem kurzen Ton?",
    ["„Ich ändere meinen Kurs nach Steuerbord“", "„Ich ändere meinen Kurs nach Backbord“", "„Meine Maschine geht rückwärts“", "„Achtung, Gefahr eines Zusammenstoßes“"],
    0, "KVR Regel 34 Buchstabe a"),
  Q("see", "signale",
    "Was bedeuten mindestens fünf kurze, schnell aufeinanderfolgende Töne?",
    ["Ein Warnsignal: Zweifel oder Unklarheit über die Absicht oder Handlung des anderen Fahrzeugs", "Das Ankermanöver ist abgeschlossen", "Beginn einer Nebelperiode", "Das Fahrzeug hat einen Notfall an Bord"],
    0, "KVR Regel 34 Buchstabe d"),
  Q("see", "navigation",
    "Welche Bedeutung hat eine grüne Tonne mit spitzem (kegelförmigem) Topzeichen im deutschen Betonnungssystem (IALA-Region A) beim Einlaufen von See her?",
    ["Sie bezeichnet die Steuerbordseite des Fahrwassers", "Sie bezeichnet die Backbordseite des Fahrwassers", "Sie markiert eine gefährliche Einzelgefahrenstelle", "Sie zeigt eine Fahrwassermitte an"],
    0, "IALA-Betonnungssystem Region A", { diagram: "buoyStarboard" }),
  Q("see", "navigation",
    "Welche Bedeutung hat eine rote Tonne mit stumpfem (zylindrischem) Topzeichen beim Einlaufen von See her?",
    ["Sie bezeichnet die Backbordseite des Fahrwassers", "Sie bezeichnet die Steuerbordseite des Fahrwassers", "Sie zeigt eine sichere Ankerstelle an", "Sie markiert die Fahrwassermitte"],
    0, "IALA-Betonnungssystem Region A", { diagram: "buoyPort" }),
  Q("see", "navigation",
    "Wie ist ein nördliches Kardinalzeichen gekennzeichnet?",
    ["Zwei schwarze Kegel-Topzeichen übereinander, beide mit der Spitze nach oben, gelb-schwarze Farbaufteilung (schwarz oben)", "Zwei Kegel mit der Spitze nach unten", "Ein rot-weiß gestreifter Aufbau ohne Topzeichen", "Ein einzelner gelber Ball"],
    0, "IALA-Kardinalsystem", { diagram: "cardinalNorth" }),
  Q("see", "navigation",
    "Wie ist ein südliches Kardinalzeichen gekennzeichnet?",
    ["Zwei schwarze Kegel-Topzeichen übereinander, beide mit der Spitze nach unten, gelb-schwarze Farbaufteilung (schwarz unten)", "Zwei Kegel mit der Spitze nach oben", "Ein grünes Licht ohne Topzeichen", "Ein rotes Blinklicht mit Glocke"],
    0, "IALA-Kardinalsystem", { diagram: "cardinalSouth" }),
  Q("see", "navigation",
    "Wozu dient ein Kardinalzeichen?",
    ["Es zeigt an, auf welcher Seite (Nord, Ost, Süd oder West) einer Gefahrenstelle sicher vorbeigefahren werden kann", "Es markiert ausschließlich Ankerverbotszonen", "Es ersetzt die Fahrwasserbetonnung vollständig", "Es kennzeichnet Bereiche für Wassersport"],
    0, "IALA-Kardinalsystem"),
  Q("see", "wetter",
    "Was versteht man unter „Ebbe“?",
    ["Das Fallen des Wasserstandes zwischen Hoch- und nachfolgendem Niedrigwasser", "Das Steigen des Wasserstandes", "Eine Sturmwarnung", "Eine Strömung, die nur bei Vollmond auftritt"],
    0, "Gezeitenkunde"),
  Q("see", "wetter",
    "Was versteht man unter „Flut“?",
    ["Das Steigen des Wasserstandes zwischen Niedrig- und nachfolgendem Hochwasser", "Das Fallen des Wasserstandes", "Eine Wetterwarnung vor Starkregen", "Der niedrigste Wasserstand des Jahres"],
    0, "Gezeitenkunde"),
  Q("see", "wetter",
    "Wo erhält ein Sportbootführer amtliche Sturmwarnungen für die Seeschifffahrt?",
    ["Über den Seewetterbericht des Deutschen Wetterdienstes (u. a. per Funk/NAVTEX)", "Ausschließlich über soziale Netzwerke", "Nur durch Beobachtung anderer Boote", "Sturmwarnungen werden nicht amtlich herausgegeben"],
    0, "Seewetterdienst des Deutschen Wetterdienstes (DWD)"),
  Q("see", "sicherheit",
    "Welches Handzeichen gilt international als Seenotzeichen, wenn kein Funkgerät verfügbar ist?",
    ["Langsames, wiederholtes Auf- und Abbewegen der seitlich ausgestreckten Arme", "Winken mit einer Hand über dem Kopf ohne weitere Bedeutung", "Beide Arme vor der Brust verschränken", "Ein Winken mit einem weißen Handtuch bedeutet ausschließlich Gruß"],
    0, "KVR Anlage IV – Seenotsignale"),
  Q("see", "sicherheit",
    "Welche Bedeutung hat eine orangefarbene Rauchsignal-Abgabe auf See?",
    ["Sie ist ein anerkanntes Seenotsignal bei Tage", "Sie zeigt lediglich die Windrichtung an, ohne Notbedeutung", "Sie ist ein Signal für „Fahrzeug vor Anker“", "Sie bedeutet „Angelfischerei im Gange“"],
    0, "KVR Anlage IV – Seenotsignale"),
  Q("see", "recht",
    "Wie sollen sich Sportfahrzeuge grundsätzlich gegenüber der Berufsschifffahrt in engen Hauptschifffahrtswegen verhalten?",
    ["Sie sollen Hauptschifffahrtswege der Berufsschifffahrt möglichst meiden bzw. ihr nicht die Fahrt erschweren", "Sportboote haben in jedem Fall Vorfahrt vor der Berufsschifffahrt", "Es bestehen keine besonderen Rücksichtnahmepflichten", "Sportboote dürfen Hauptfahrwasser nachts nicht befahren, tagsüber ohne Einschränkung"],
    0, "Seeschifffahrtsstraßenordnung (SeeSchStrO), Regelung zum Verhalten von Sportfahrzeugen"),
  Q("see", "verhalten",
    "Ein Fahrzeug unter Segel führt gleichzeitig den Motor mit. Als was gilt es verkehrsrechtlich?",
    ["Als Maschinenfahrzeug, mit den entsprechenden Ausweich- und Lichterregeln", "Weiterhin uneingeschränkt als Segelfahrzeug mit Vorfahrt", "Als manövrierunfähiges Fahrzeug", "Die Einstufung ist rechtlich ohne Bedeutung"],
    0, "KVR Regel 3 Buchstabe c / Regel 25 Buchstabe e"),
  Q("see", "navigation",
    "Was ist eine Seemeile (international nautical mile)?",
    ["1852 Meter", "1000 Meter", "1609 Meter (entspricht der Landmeile)", "500 Meter"],
    0, "Internationale Definition der Seemeile"),
  Q("see", "navigation",
    "Was gibt ein Knoten als Geschwindigkeitseinheit an?",
    ["Seemeilen pro Stunde", "Kilometer pro Stunde", "Meter pro Sekunde", "Seemeilen pro Minute"],
    0, "Nautische Geschwindigkeitseinheit"),

  // ---------------------------------------------------------------
  // PAKET: BINNENSPEZIFISCHE FRAGEN
  // ---------------------------------------------------------------
  Q("binnen", "verhalten",
    "Wie begegnen sich zwei Fahrzeuge auf einer Binnenwasserstraße im Regelfall (Backbord an Backbord)?",
    ["Jedes Fahrzeug hält sich an sein Steuerbord und weicht nach Steuerbord aus", "Beide halten sich an ihr Backbord", "Der Talfahrer weicht immer vollständig aus dem Fahrwasser", "Es gibt in der Binnenschifffahrt keine Begegnungsregel"],
    0, "BinSchStrO § 6.04 – Begegnen"),
  Q("binnen", "verhalten",
    "Wer ist beim Überholen auf Binnenwasserstraßen grundsätzlich ausweichpflichtig?",
    ["Das überholende Fahrzeug muss den nötigen Abstand einhalten und darf den überholten Fahrzeug nicht behindern", "Das überholte Fahrzeug muss dem überholenden ausweichen", "Überholen ist auf Binnenwasserstraßen generell verboten", "Nur die Berufsschifffahrt darf überholen"],
    0, "BinSchStrO § 6.09 – Überholen"),
  Q("binnen", "verhalten",
    "Welches Fahrzeug hat beim Begegnen von Berg- und Talfahrer auf engen Flussstrecken häufig Vorfahrt?",
    ["In der Regel der Talfahrer, da er schwerer zu bremsen bzw. zu manövrieren ist", "Immer der Bergfahrer", "Das kleinere Fahrzeug", "Es gilt ausschließlich „rechts vor links“"],
    0, "BinSchStrO, Sonderregeln zur Bergfahrt/Talfahrt (streckenabhängig, z. B. am Rhein)"),
  Q("binnen", "signale",
    "Was bedeutet ein weißes, allseits sichtbares Funkellicht (schnelle Blinkfolge) an einem Fahrzeug in der Binnenschifffahrt?",
    ["Das Fahrzeug beabsichtigt zu wenden bzw. weist auf ein bevorstehendes Wendemanöver hin", "Das Fahrzeug hat einen Maschinenschaden", "Das Fahrzeug fordert zum Überholen auf", "Es handelt sich um ein Fahrgastschiff im Linienverkehr"],
    0, "BinSchStrO, Vorschriften über Wendesignale"),
  Q("binnen", "signale",
    "Welche grundlegende Bedeutung hat ein einzelner kurzer Ton in der Binnenschifffahrt bei einem Richtungswechsel?",
    ["„Ich richte meinen Kurs nach Steuerbord“", "„Ich richte meinen Kurs nach Backbord“", "„Ich gehe rückwärts“", "„Ich ankere“"],
    0, "BinSchStrO, Schallzeichen bei Kursänderung"),
  Q("binnen", "recht",
    "Was ist beim Einfahren in eine Schleuse grundsätzlich zu beachten?",
    ["Die Anweisungen des Schleusenpersonals bzw. der Lichtsignale sind zu befolgen, Geschwindigkeit ist rechtzeitig zu reduzieren", "Sportboote dürfen Schleusen ohne Anmeldung und ohne Rücksicht auf Signale befahren", "Es gilt grundsätzlich freie Reihenfolge unabhängig von Signalen", "Schleusen dürfen von Sportbooten nicht benutzt werden"],
    0, "BinSchStrO, Kapitel 6 – Vorschriften für das Schleusen"),
  Q("binnen", "navigation",
    "Welches Topzeichen tragen Steuerbordtonnen (rechte Fahrwasserseite bei Bergfahrt) im deutschen Binnenbetonnungssystem üblicherweise?",
    ["Ein grüner, spitzer (kegelförmiger) Aufbau", "Ein roter, zylindrischer Aufbau", "Ein gelbes Kreuz", "Ein schwarzer Ball"],
    0, "Binnen-Betonnungssystem (System B)", { diagram: "buoyStarboard" }),
  Q("binnen", "navigation",
    "Welches Topzeichen tragen Backbordtonnen (linke Fahrwasserseite bei Bergfahrt) im deutschen Binnenbetonnungssystem üblicherweise?",
    ["Ein roter, stumpfer bzw. zylindrischer Aufbau", "Ein grüner, spitzer Aufbau", "Ein gelbes X", "Ein weißer Ball"],
    0, "Binnen-Betonnungssystem (System B)", { diagram: "buoyPort" }),
  Q("binnen", "recht",
    "Was regelt Kapitel 9 der Binnenschifffahrtsstraßen-Ordnung im Kern?",
    ["Besondere Vorschriften für den Wassersport, unter anderem für Kleinfahrzeuge", "Ausschließlich das Befahren von Häfen", "Die technische Zulassung von Berufsschiffen", "Die Ausbildung von Berufsschiffsführern"],
    0, "BinSchStrO, Kapitel 9 – Wassersport"),
  Q("binnen", "verhalten",
    "Wie müssen sich Kleinfahrzeuge (u. a. Sportboote) gegenüber Fahrzeugen der Berufsschifffahrt in engen Fahrrinnen grundsätzlich verhalten?",
    ["Sie müssen ihnen ausweichen und dürfen sie nicht am sicheren Manövrieren hindern", "Kleinfahrzeuge haben stets Vorfahrt, unabhängig von der Fahrwasserbreite", "Es besteht keine besondere Rücksichtnahmepflicht", "Nur bei Nacht müssen Kleinfahrzeuge ausweichen"],
    0, "BinSchStrO, Kapitel 9 – Wassersport / allgemeiner Sorgfaltsgrundsatz"),
  Q("binnen", "recht",
    "Was bedeutet das Tafelzeichen mit einem roten Kreis auf weißem Grund und schwarzem Balken (Verbotszeichen) an einer Wasserstraße typischerweise?",
    ["Ein Verbot, z. B. Durchfahrtsverbot oder Verbot einer bestimmten Handlung", "Eine allgemeine Geschwindigkeitsempfehlung", "Eine Ankerstelle für Sportboote", "Eine Fährverbindung"],
    0, "Binnenschifffahrtszeichen-Verordnung (Tafelzeichen), analog zur BinSchStrO Anlage 7"),
  Q("binnen", "recht",
    "Welche Bedeutung hat ein blaues Tafelzeichen mit weißem Pfeil in der Binnenschifffahrt häufig?",
    ["Ein Gebotszeichen, z. B. Gebot, die angegebene Fahrwasserseite zu benutzen", "Ein reines Werbezeichen ohne Verkehrsbedeutung", "Ein Verbotszeichen", "Eine touristische Sehenswürdigkeit"],
    0, "Binnenschifffahrtszeichen-Verordnung (Gebotszeichen)"),
  Q("binnen", "sicherheit",
    "Was ist beim Befahren von Wasserstraßen mit starker Berufsschifffahrt hinsichtlich des Sogs und Wellenschlags an Buhnenfeldern zu beachten?",
    ["Ausreichend Abstand halten, da vorbeifahrende Großschiffe Sog- und Wellenwirkung erzeugen können, die kleine Boote gefährden", "Sog und Wellenschlag sind bei Sportbooten ohne Bedeutung", "Nur bei Nacht besteht eine erhöhte Gefahr durch Sog", "Buhnenfelder dürfen nur von Berufsschifffahrt befahren werden"],
    0, "Allgemeiner Sorgfaltsgrundsatz, seemannschaftliche Praxis"),
  Q("binnen", "verhalten",
    "Was gilt grundsätzlich beim Kreuzen eines Fährbetriebs (Gierfähre/Fähre) auf einer Binnenwasserstraße?",
    ["Der Fährbetrieb hat in der Regel Vorfahrt, andere Fahrzeuge müssen ausweichen bzw. warten", "Sportboote haben grundsätzlich Vorfahrt vor Fähren", "Fähren dürfen nur nachts fahren", "Es gibt keine besonderen Regeln beim Kreuzen von Fährbetrieben"],
    0, "BinSchStrO, Sonderregeln für Fährverkehr"),
  Q("binnen", "wetter",
    "Warum kann Hochwasser auf Binnenwasserstraßen zu Fahrverboten für Sportboote führen?",
    ["Wegen erhöhter Fließgeschwindigkeit, Sog- und Kollisionsgefahr sowie eingeschränkter Durchfahrtshöhen an Brücken", "Hochwasser hat keinen Einfluss auf die Befahrbarkeit", "Nur die Berufsschifffahrt ist von Hochwasserständen betroffen", "Hochwasser erhöht ausschließlich die Sichtweite"],
    0, "Hochwassermarken-Regelungen der Wasserstraßen- und Schifffahrtsverwaltung"),
  Q("binnen", "recht",
    "Welche Verordnung regelt Aufbau, Umfang und Ablauf der Sportbootführerschein-Prüfungen in Deutschland?",
    ["Die Sportbootführerschein-Verordnung (SpFV)", "Die Straßenverkehrsordnung (StVO)", "Das Seearbeitsgesetz", "Die Binnenschifffahrtsaufgabenverordnung"],
    0, "Sportbootführerschein-Verordnung (SpFV)"),
  Q("binnen", "verhalten",
    "Wie ist der Geltungsbereich des SBF Binnen gegenüber dem SBF See grundsätzlich abgegrenzt?",
    ["SBF Binnen gilt für Binnenschifffahrtsstraßen, SBF See für Seeschifffahrtsstraßen und Küstengewässer", "Beide Scheine gelten ausschließlich auf denselben Gewässern", "SBF Binnen gilt zusätzlich automatisch auch auf See", "Der Geltungsbereich richtet sich nach der Bootsgröße, nicht nach dem Gewässer"],
    0, "Sportbootführerschein-Verordnung (SpFV), Geltungsbereiche"),
  Q("binnen", "navigation",
    "Was zeigt ein grünes Funkellicht an einer Schleuseneinfahrt üblicherweise an?",
    ["Die Einfahrt ist freigegeben", "Die Einfahrt ist gesperrt", "Es handelt sich um ein Notsignal", "Es zeigt lediglich die Fahrtrichtung des Kanals an"],
    0, "BinSchStrO, Lichtsignale an Schleusen"),
  Q("binnen", "navigation",
    "Was zeigt ein rotes Licht (Dauerlicht) an einer Schleuseneinfahrt üblicherweise an?",
    ["Einfahrtverbot / Halt", "Freie Einfahrt", "Vorrang für Sportboote", "Die Schleusenkammer ist leer"],
    0, "BinSchStrO, Lichtsignale an Schleusen"),
  Q("binnen", "verhalten",
    "Was ist beim Wenden auf einer engen Binnenwasserstraße zu beachten?",
    ["Das Wendemanöver darf andere Fahrzeuge nicht gefährden und ist rechtzeitig anzukündigen, u. a. durch Schallsignal", "Wenden ist auf Binnenwasserstraßen generell verboten", "Es sind keine Ankündigungssignale erforderlich", "Wenden darf nur die Berufsschifffahrt"],
    0, "BinSchStrO, Vorschriften zum Wenden"),

  // ---------------------------------------------------------------
  // PAKET: NAVIGATION
  // ---------------------------------------------------------------
  Q("navigation", "navigation",
    "Was versteht man unter dem „rechtweisenden Kurs“?",
    ["Den Kurswinkel gemessen zwischen der geographischen (rechtweisenden) Nordrichtung und der Kurslinie", "Den auf dem Kompass abgelesenen, unkorrigierten Kurs", "Den Kurs relativ zur Windrichtung", "Den Kurs relativ zur Strömung"],
    0, "Terrestrische Navigation, Grundbegriffe"),
  Q("navigation", "navigation",
    "Was ist die missweisende Nordrichtung?",
    ["Die Richtung, in die eine frei bewegliche Magnetnadel ohne Störeinflüsse durch das Schiff zeigt (magnetisch Nord)", "Die geographische Nordrichtung", "Die vom Kreiselkompass angezeigte Nordrichtung", "Die Richtung des wahren Windes"],
    0, "Terrestrische Navigation, Grundbegriffe (Missweisung)"),
  Q("navigation", "navigation",
    "Was bezeichnet die Deviation eines Magnetkompasses?",
    ["Die durch Eisenteile und elektrische Geräte an Bord verursachte Ablenkung der Kompassnadel vom missweisenden Kurs", "Den Unterschied zwischen rechtweisendem und magnetischem Nord", "Die Abweichung des Bootes vom geplanten Kurs durch Strömung", "Die jährliche Änderung der Missweisung"],
    0, "Terrestrische Navigation, Kompasslehre"),
  Q("navigation", "navigation",
    "Wie berechnet sich der Kompasskurs (KüK) grundsätzlich aus dem rechtweisenden Kurs?",
    ["Rechtweisender Kurs minus Missweisung minus Deviation ergibt den Kompasskurs", "Rechtweisender Kurs plus Fahrtgeschwindigkeit", "Kompasskurs entspricht immer dem rechtweisenden Kurs", "Kompasskurs ist unabhängig von Missweisung und Deviation"],
    0, "Terrestrische Navigation, Kursumrechnung (Merkschema: rw – miss – dev = kp, unter Beachtung der Vorzeichen)"),
  Q("navigation", "navigation",
    "Was ist eine Kreuzpeilung?",
    ["Die Standortbestimmung durch gleichzeitige oder kurz nacheinander erfolgende Peilung von mindestens zwei bekannten Landmarken", "Die Messung der Wassertiefe an zwei Punkten", "Die Peilung eines anderen Fahrzeugs zur Kollisionsvermeidung", "Eine Methode zur Windmessung"],
    0, "Terrestrische Navigation, Standortbestimmung"),
  Q("navigation", "navigation",
    "Was zeigt der Maßstab einer Seekarte an?",
    ["Das Verhältnis zwischen einer Strecke auf der Karte und der entsprechenden Strecke in der Natur", "Die Wassertiefe in der dargestellten Region", "Die geltenden Geschwindigkeitsbegrenzungen", "Die Position der nächsten Schleuse"],
    0, "Kartenkunde"),
  Q("navigation", "navigation",
    "Worauf beziehen sich Tiefenangaben in einer Seekarte üblicherweise?",
    ["Auf den Kartennullpunkt (Seekartennull), einen festgelegten, meist niedrigen Bezugswasserstand", "Immer auf den mittleren Meeresspiegel weltweit", "Auf den höchsten je gemessenen Wasserstand", "Auf die Position des Beobachters"],
    0, "Kartenkunde, Kartennullpunkt (Chart Datum)"),
  Q("navigation", "navigation",
    "Was versteht man unter „Versetzung“ durch Strömung?",
    ["Die seitliche Abweichung des tatsächlichen Kurses über Grund vom gesteuerten Kurs durch den Wasserstrom", "Die Änderung der Kompassmissweisung über die Zeit", "Die Abweichung durch fehlerhafte Kartenkorrektur", "Die Änderung der Windrichtung während der Fahrt"],
    0, "Navigatorische Grundbegriffe, Strömungsversetzung"),
  Q("navigation", "navigation",
    "Wozu dient ein Log an Bord?",
    ["Zur Messung der Fahrtgeschwindigkeit bzw. der zurückgelegten Distanz durchs Wasser", "Zur Messung der Wassertiefe", "Zur Bestimmung der Windrichtung", "Zur Aufzeichnung von Funksprüchen"],
    0, "Navigatorische Ausrüstung"),
  Q("navigation", "navigation",
    "Was liefert ein GPS-Empfänger primär?",
    ["Die aktuelle Position über Grund anhand von Satellitensignalen", "Die genaue Wassertiefe unter dem Kiel", "Die Windgeschwindigkeit", "Die Kompassmissweisung am jeweiligen Ort"],
    0, "Satellitennavigation, Grundlagen"),
  Q("navigation", "navigation",
    "Was bedeutet die Abkürzung „SOG“ in der Navigation?",
    ["Geschwindigkeit über Grund (Speed Over Ground)", "Standort ohne Genauigkeit", "Seemeilen ohne Gezeitenkorrektur", "Sichtweite ohne Gewähr"],
    0, "Navigatorische Fachbegriffe (GPS-Navigation)"),
  Q("navigation", "navigation",
    "Wie wird eine Position in geographischen Koordinaten angegeben?",
    ["Durch geographische Breite und Länge, jeweils in Grad, Minuten (und Sekunden bzw. Dezimalminuten)", "Ausschließlich durch die Entfernung zur nächsten Küste", "Durch die Nummer der nächstgelegenen Tonne", "Durch Kompasskurs und Uhrzeit"],
    0, "Grundlagen der Positionsangabe"),
  Q("navigation", "navigation",
    "Was ist unter „Gezeitenstrom“ zu verstehen?",
    ["Die durch Ebbe und Flut verursachte horizontale Wasserbewegung", "Ein Fluss, der ins Meer mündet", "Die vertikale Änderung des Wasserstands allein", "Ein Starkwindereignis über dem Meer"],
    0, "Gezeitenkunde"),
  Q("navigation", "navigation",
    "Wann tritt eine Springtide auf?",
    ["Bei Voll- oder Neumond, wenn Sonne und Mond auf einer Linie stehen und sich ihre Anziehungskräfte verstärken", "Nur zur Tag- und Nachtgleiche im Frühjahr", "Ausschließlich im Winter", "Wenn kein Mond am Himmel sichtbar ist, unabhängig von der Mondphase"],
    0, "Gezeitenkunde, Spring- und Nipptide"),
  Q("navigation", "navigation",
    "Was ist eine Nipptide?",
    ["Eine Gezeit mit geringerem Tidenhub, die bei Halbmond auftritt, wenn sich die Anziehungskräfte von Sonne und Mond teilweise aufheben", "Die höchste Flut des Jahres", "Ein anderes Wort für Ebbe", "Ein Sturmereignis mit Hochwasser"],
    0, "Gezeitenkunde, Spring- und Nipptide"),
];

if (typeof module !== "undefined") module.exports = { PACKAGES, CATEGORIES, QUESTIONS };
